version: "3.8" # Specify the Docker Compose version

services:
  influxdb2:
    image: influxdb:latest
    ports:
      - "8086:8086" # Expose InfluxDB HTTP API port to the host
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin # InfluxDB username
      DOCKER_INFLUXDB_INIT_PASSWORD: HTL22_"2025 # InfluxDB password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: HTL22_"2025 # InfluxDB admin token
      DOCKER_INFLUXDB_INIT_ORG: IotIsSimple # Organization name
      DOCKER_INFLUXDB_INIT_BUCKET: Iot-SysDev # Bucket name
    volumes:
      - influxdb2-data:/var/lib/influxdb2 # Persist data
    networks:
      - my_network # Connect to custom network

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883" # Expose MQTT port to the host
    environment:
      MOSQUITTO_USER: admin # Username for Mosquitto
      MOSQUITTO_PASSWORD: HTL22_"2025 # Password for Mosquitto
    volumes:
      - ./mos.conf:/mosquitto/config/mosquitto.conf
    networks:
      - my_network # Connect to custom network

  node-app:
    image: mqtt-influxdb-client # Use existing Docker image for the Node.js app
    depends_on:
      - influxdb2
      - mosquitto
    environment:
      MQTT_BROKER_URL: "mqtt://mosquitto" # Mosquitto broker URL
      INFLUX_URL: "http://influxdb2:8086" # InfluxDB URL
      INFLUX_TOKEN: HTL22_"2025 # InfluxDB token
      INFLUX_ORG: IotIsSimple # InfluxDB organization
      INFLUX_BUCKET: Iot-SysDev # InfluxDB bucket
    networks:
      - my_network # Connect to custom network

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb2
    environment:
      GF_SECURITY_ADMIN_PASSWORD: HTL22_"2025 # Grafana admin password
    ports:
      - "3001:3000" # Expose Grafana UI to the host
    volumes:
      - grafana-data:/var/lib/grafana # Persist Grafana data
    networks:
      - my_network # Connect to custom network

volumes:
  influxdb2-data: # Volume for InfluxDB data
  grafana-data: # Volume for Grafana data

networks:
  my_network: # Define a custom network
